const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={roles:[],scenario:null};

async function getJSON(path){const res=await fetch(path);if(!res.ok)throw new Error(`Failed to load ${path}`);return res.json()}
function reveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -6%'});$$('[data-reveal], [data-reveal-block]').forEach((el,i)=>{el.style.transitionDelay=`${Math.min(i%5,4)*70}ms`;io.observe(el)})}
function progress(){const el=$('#progress');let ticking=false;const update=()=>{const h=document.documentElement.scrollHeight-innerHeight;el.style.width=`${h>0?(scrollY/h)*100:0}%`;ticking=false};addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(update);ticking=true}},{passive:true});update()}
function nav(){const trigger=$('#menuTrigger'),menu=$('#mobileMenu');const set=open=>{trigger.setAttribute('aria-expanded',String(open));menu.classList.toggle('is-open',open);menu.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('menu-open',open)};trigger.addEventListener('click',()=>set(!menu.classList.contains('is-open')));$$('a',menu).forEach(a=>a.addEventListener('click',()=>set(false)));addEventListener('keydown',e=>{if(e.key==='Escape')set(false)})}
function cinematicArt(el,type='scenario'){el.innerHTML=`<div class="card-art ${type==='mafia'?'mafia-art':''}"></div>`}
function renderScenarios(){const rail=$('#scenarioRail');rail.innerHTML='';const s=state.scenario;const card=document.createElement('article');card.className='scenario-card';card.innerHTML=`<div class="card-art"></div><div class="card-content"><span class="tag">${s.tag||'فعال'} / ${s.type}</span><h3>${s.title}</h3><p>${s.summary}</p></div>`;rail.append(card);$('#scenarioCount').textContent='01';const detail=$('#scenarioDetail');detail.innerHTML=`<span class="detail-tag">ACTIVE SCENARIO</span><h3 class="detail-title">${s.title}</h3><p class="detail-summary">${s.summary}</p><div class="detail-info">${s.info.map(x=>`<span>${x}</span>`).join('')}</div>`;renderStory(s);renderStats(s)}
function renderStory(s){$('#storySteps').innerHTML=s.story.map((x,i)=>`<div class="story-step" data-reveal><span>0${i+1}</span><p>${x}</p></div>`).join('');requestAnimationFrame(reveal)}
function renderStats(s){$('#statGrid').innerHTML=s.stats.map(x=>`<div class="stat reveal-block"><strong>${x.value}</strong><span>${x.label}</span></div>`).join('');requestAnimationFrame(reveal)}
function renderRoles(){const rail=$('#roleRail');const render=side=>{rail.innerHTML=state.roles.filter(r=>side==='all'||r.side===side).map(r=>`<article class="role-card ${r.side==='mafia'?'side-mafia':''}" data-role="${r.id}" tabindex="0"><div class="card-art"></div><div class="card-content"><span class="side">${r.label}</span><h3>${r.name}</h3><p>${r.identity}</p></div></article>`).join('');$$('.role-card',rail).forEach(card=>{card.addEventListener('click',()=>openSheet(card.dataset.role));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')openSheet(card.dataset.role)})})};render('all');$$('#roleFilter button').forEach(b=>b.addEventListener('click',()=>{$$('#roleFilter button').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');render(b.dataset.side)}))}
function openSheet(id){const r=state.roles.find(x=>x.id===id);if(!r)return;$('#sheetSide').textContent=r.label;$('#sheetName').textContent=r.name;$('#sheetIdentity').textContent=r.identity;$('#sheetAbility').textContent=r.ability;$('#sheetArt').className=`sheet-art ${r.side==='mafia'?'mafia-art':''}`;$('#roleSheet').classList.add('is-open');$('#sheetBackdrop').classList.add('is-open');$('#roleSheet').setAttribute('aria-hidden','false');document.body.classList.add('sheet-open');$('#sheetClose').focus()}
function closeSheet(){$('#roleSheet').classList.remove('is-open');$('#sheetBackdrop').classList.remove('is-open');$('#roleSheet').setAttribute('aria-hidden','true');document.body.classList.remove('sheet-open')}
function envelope(){const e=$('#envelope'),stage=e.closest('.envelope-stage'),hint=$('#envelopeHint'),close=$('#closeEnvelope');const open=()=>{e.classList.add('is-open');stage.classList.add('is-open');hint.textContent='پرونده باز شد'};e.addEventListener('click',open);close.addEventListener('click',()=>{e.classList.remove('is-open');stage.classList.remove('is-open');hint.textContent='لمس کن تا باز شود';e.focus()})}
async function boot(){nav();progress();envelope();$('#sheetClose').addEventListener('click',closeSheet);$('#sheetBackdrop').addEventListener('click',closeSheet);addEventListener('keydown',e=>{if(e.key==='Escape')closeSheet()});try{[state.roles,state.scenario]=await Promise.all([getJSON('data/roles.json'),getJSON('data/scenarios.json').then(x=>x[0])]);renderScenarios();renderRoles()}catch(err){console.error('Night War data error',err)}finally{reveal()}}
boot();
